version: '3.8'
services:
  traefik:
    image: traefik
    restart: unless-stopped
    command:
      # ── Core ─────────────────────────────────────────
      - --api.insecure=true                     # Panel en :8080
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # ── Entrypoints ─────────────────────────
      - --entrypoints.web.address=:80           # HTTP  (Let’s Encrypt challenge)
      - --entrypoints.websecure.address=:443    # HTTPS producción
      # ── ACME (HTTP-01) ──────────────────────
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=${SSL_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    labels:
      # Redirección a HTTPS excepto para el challenge
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.redirect.rule=hostregexp(`{host:.+}`) && !PathPrefix(`/.well-known/acme-challenge/`)
      - traefik.http.routers.redirect.entrypoints=web
      - traefik.http.routers.redirect.middlewares=redirect-to-https
    ports```
    ports:
      - "80:80"     # << Cambiado (era 8001:80)
      - "8443:443"  # Puedes dejar 8443 o pasar a 443:443 si ese puerto está libre
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ncat:
    image: stephengpope/no-code-architects-toolkit:latest
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.ncat.rule=Host(`tools.novapsis.site`)
      - traefik.http.routers.ncat.entrypoints=websecure
      - traefik.http.routers.ncat.tls=true
      - traefik.http.routers.ncat.tls.certresolver=le   # mismo nombre que arriba
      - traefik.http.services.ncat.loadbalancer.server.port=8080
    volumes:
      - nca_storage:/tmp
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs
    restart: unless-stopped

volumes:
  traefik_data:
  nca_storage:
  storage:
  logs:
